#!/usr/bin/env bash
cz=0
cd=0
for i in $(seq 1 100);do
    if [ $(($RANDOM % 2)) -eq 1 ];then
	echo -n "ズン "
	cz=$(expr $cz + 1)
	cd=0
    else echo -n "ドコ "
	 if [ $cd -eq 0 ] && [ $cz -ge 4 ]
	 then echo ""
	      cowsay "キ・ ヨ・シ！"
	 fi
	 echo ""
	 cz=0;cd=$(expr $cd + 1)
    fi
done
