#!/usr/bin/env python3

import sys
from unicodedata import name, normalize


def apaato_watto(apaato=u'㌀', watto=u'㍗', n=0):
    error_count = 0
    if ord(apaato) < ord(watto):
        start = ord(apaato)
        end = ord(watto)
    else:
        start = ord(watto)
        end = ord(apaato)

    charactor_list = range(start - n, end + 1 + n)
    print('charactor list : ' + str(charactor_list))
    if len(charactor_list) > 300:
        print('too many charactors are listed')
        return

    for i in charactor_list:
        try:
            print(chr(i), ':',
                  hex(i), ':',
                  name(chr(i)), ':',
                  normalize('NFKC', chr(i)))
        except:
            error_count += 1

    print("error count : " + str(error_count))


if __name__ == '__main__':

    if len(sys.argv) > 2:
        n = 0
        if len(sys.argv) > 3:
            n = int(sys.argv[3])
        apaato_watto(apaato=str(sys.argv[1]), watto=str(sys.argv[2]), n=n)
    else:
        apaato_watto()
